### PR TITLE
Created a Metamask docs contributor list via github api

### PR DESCRIPTION
**Pull request by timothius2005**
WIP

### CODE REVIEW

**Comment by BboyAkers** [comment]
Going to make some changes and add the MetaMask Extension, and MetaMask Mobile contributor list 🙂.

**Comment by BboyAkers** [comment]
@Gudahtt @kumavis input? 🙂

**Comment by whymarrh** [comment]
The build is failing with the following error:

```
yarn run v1.22.4
$ vuepress build docs
wait Extracting site metadata...
tip Apply theme @vuepress/theme-default ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/last-updated (i.e. "@vuepress/plugin-last-updated") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin smooth-scroll (i.e. "vuepress-plugin-smooth-scroll") ...
tip Apply plugin @vuepress/back-to-top (i.e. "@vuepress/plugin-back-to-top") ...
tip Apply plugin @vuepress/pwa (i.e. "@vuepress/plugin-pwa") ...
tip Apply plugin @vuepress/medium-zoom (i.e. "@vuepress/plugin-medium-zoom") ...
tip Apply plugin redirect (i.e. "vuepress-plugin-redirect") ...
tip Apply plugin dehydrate (i.e. "vuepress-plugin-dehydrate") ...
tip Apply plugin tabs (i.e. "vuepress-plugin-tabs") ...
[info] [webpackbar] Compiling Client
[info] [webpackbar] Compiling Server
[success] [webpackbar] Server: Compiled successfully in 13.43s
[success] [webpackbar] Client: Compiled successfully in 17.14s
wait Rendering static HTML...
[Vue warn]: Error in created hook: "ReferenceError: fetch is not defined"

found in

---> <GithubContributor>
       <Tab>
         <Tabs>
           <VE299f046>
             <Content>
               <Page>
                 <Layout>
                   <GlobalLayout>
                     <Root>
error Error rendering /guide/contributors.html: false
undefined
ReferenceError: fetch is not defined
    at VueComponent.fetchContributorsList (docs/.vuepress/components/GithubContributor.vue:41:0)
    at VueComponent.created (docs/.vuepress/components/GithubContributor.vue:50:0)
    at invokeWithErrorHandling (/home/circleci/project/node_modules/vue/dist/vue.runtime.common.dev.js:1850:57)
    at callHook (/home/circleci/project/node_modules/vue/dist/vue.runtime.common.dev.js:4207:7)
    at VueComponent.Vue._init (/home/circleci/project/node_modules/vue/dist/vue.runtime.common.dev.js:4989:5)
    at new VueComponent (/home/circleci/project/node_modules/vue/dist/vue.runtime.common.dev.js:5134:12)
    at createComponentInstanceForVnode (/home/circleci/project/node_modules/vue-server-renderer/build.dev.js:8184:10)
    at renderComponentInner (/home/circleci/project/node_modules/vue-server-renderer/build.dev.js:8408:40)
    at renderComponent (/home/circleci/project/node_modules/vue-server-renderer/build.dev.js:8383:5)
    at resolve (/home/circleci/project/node_modules/vue-server-renderer/build.dev.js:8451:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1
```

We might need to change how we're fetching the list to get this to build correctly?

**Comment by BboyAkers** [comment]
@whymarrh I moved the fetch call into the created() lifecycle method. Hopefully that fixes it! Waiting on @timothius2005 to merge my changes.

**Comment by whymarrh** [comment]
The error is still there—I can look into it this week. I haven't really played with the build here but this might be because the build is running & the component is created in a Node.js environment. Can we use the [`mounted`](https://vuejs.org/v2/api/#mounted) function instead? Would that run in the browser context?

**Comment by BboyAkers** [comment]
I'll test it out!

**Comment by BboyAkers** [comment]
@whymarrh should we merge this? It still works on local but I'm not sure if we should modify the build process.

**Comment by whymarrh** [comment]
> It still works on local but I'm not sure if we should modify the build process.

We'll need to fix the build to get this to work. I can take it on but it'll be a while before I can get to it.

**Comment by whymarrh** [comment]
I switched the method from `created` to `mounted` in 924e1fc. The `created` method will run during the build where the `window` global doesn't exist but `mounted` will run in the browser. I tested it locally and it seems to work!

**Review by BboyAkers — APPROVED** [review]

**Pull request merged**
