### PR TITLE
Move wallet_*snap methods to Snaps docs

### LINKED ISSUE #1283: Move `wallet_*snap` API methods to Snaps docs
The four Snaps API methods callable by dapps (`wallet_*snap`) don't work with the interactive API plugin, so we need to move them back to a location in the Snaps docs. Also update `api-specs` repo to remove them from the interactive reference.

### PR DESCRIPTION
**Pull request by alexandratran**
# Description

Move `wallet_snap`, `wallet_invokeSnap`, `wallet_getSnaps`, and `wallet_requestSnap` docs to a new reference page in the Snaps docs, "Wallet API for Snaps." Update context and links accordingly.

Also see https://github.com/MetaMask/api-specs/pull/218, which removes these methods from the interactive reference.

## Issue(s) fixed

Fixes #1283

## Preview

https://docs.metamask.io/1283-move-snaps-methods/snaps/reference/wallet-api-for-snaps/

## Checklist

Complete this checklist before merging your PR:

- [x] If this PR contains a major change to the documentation content, I have added an entry to the top of the ["What's new?"](https://github.com/MetaMask/metamask-docs/blob/main/docs/whats-new.md) page.
- [ ] The proposed changes have been reviewed and approved by a member of the documentation team.

### CODE REVIEW

**Review by vandan — APPROVED** [review]
As long as someone from Snaps can review the manually written API specs, everything else lgtm

**Review by Montoya — CHANGES_REQUESTED** [review]
Everything looks good, but this page also needs to be updated: https://docs.metamask.io/snaps/how-to/connect-to-a-snap/

**Comment by alexandratran** [comment]
@Montoya Good catch, fixed along with one other link

**Review by Montoya — APPROVED** [review]

**Review by joaniefromtheblock — APPROVED** [review]
LGTM

**Pull request merged**
