### PR TITLE
Add how-to page for `initialConnections`

### PR DESCRIPTION
**Pull request by ziad-saab**
# Description

Add a how-to page for `initialConnections`

## Issue(s) fixed

Fixes #

## Checklist

Complete this checklist before merging your PR:

- [ ] If this PR contains a major change to the documentation content, I have added an entry to the top of the ["What's new?"](https://github.com/MetaMask/metamask-docs/blob/main/docs/whats-new.md) page.
- [ ] The proposed changes have been reviewed and approved by a member of the documentation team.

### CODE REVIEW

**Review by alexandratran — APPROVED** [review]
I moved the content under "How to" and removed it from the permission reference to avoid duplication. LGTM.

**Review by Montoya — APPROVED** [review]

**Comment by Montoya** [comment]
Hi @ziad-saab, I did not intend to remove the section on `initialConnections` from the permissions page and move it to a how to page. `initialConnections` is part of Snaps permissions and should remain in the permissions section as it is documented. What I wanted to do was have a longer how to guide on how to use this unique permission with example dapp code and some way to convey how the flow changes when the dapp is able to auto-connect. 

Please revert the permissions page and flesh out the how to page.

**Review by Montoya — CHANGES_REQUESTED** [review]
See above comment

Please feel free to use the Voyager Snap source code in your example, see the `site` and `snap` packages for relevant content. https://github.com/Consensys/linea-voyager-snap

**Comment by alexandratran** [comment]
@Montoya Sorry, I was the one who moved it from the Permissions reference, since the added content seemed to be exactly the same and I wanted to avoid duplication. I've now added it back to Permissions, and added an example link to the How to page. Let me know if there's a specific way you want to flesh out the How to page further (is there a particular code sample from the dapp package we should include?)

**Review by Montoya — DISMISSED** [review]

**Review by alexandratran — APPROVED** [review]
Edited the updated instructions, LGTM.

**Review by Montoya — APPROVED** [review]

**Pull request merged**
