### PR TITLE
Add Snaps best practices section

### LINKED ISSUE #1163: Add "best practices" section
Add "Best practices" section under "Learn," and add Snaps design guidelines and security guidelines to that section. May need to split out general design guidelines from "Design a Snap installation flow."

### PR DESCRIPTION
**Pull request by alexandratran**
Adds a "Best practices" section under the "Learn" top-level section. Renames the Snaps design and security guidelines pages and adds them to this section. Fixes #1163.

Preview: https://docs.metamask.io/1163-snaps-best-practices/snaps/learn/best-practices/

### CODE REVIEW

**Comment by Montoya** [comment]
Build is failing due to duplicate routes btw

**Review by Montoya — APPROVED** [review]

**Review by bgravenorst — APPROVED** [review]
lgtm

**Review by joaniefromtheblock — APPROVED** [review]
LGTM

**Comment by Montoya** [comment]
"Dev Ex" was requested for review but it should have been Snaps. Regardless, I think this can be merged.

**Pull request merged**
