### PR TITLE
Update rpc-api.md

### PR DESCRIPTION
**Pull request by zzmp**
Include note about allowlisting the extension origin when switching chains.

### CODE REVIEW

**Comment by zzmp** [comment]
I'm not sure if services (like infura) allow allowlisting the chrome-extension:// protocol (although it accepted it into the list when I tried). I'm also not sure that the request is sent from that origin, although I know it is sent from the background page (because that's where I observed this error).

It may be necessary to instead use a publicly accessible JSON-RPC URL when adding a chain, so that MetaMask's call to eth_chainId (which seems to be made to verify the URL before adding the chain) does not fail.

**Comment by Gudahtt** [comment]
Thanks for the contribution! Unfortunately I'm not sure we should include this advice, because anyone implementing such an allowlist would end up blocking all Firefox users. Firefox extensions do not have any static origin (it gets generated at install-time), so there is no equivalent origin that could be used to allow just the legitimate Firefox extension.

**Comment by Gudahtt** [comment]
Well, I guess we could list `moz-extension://` for Firefox, allowing _all_ traffic from Firefox extensions. Not ideal but that might work for some people. I don't know if Infura's origin allowlist would accept an entire scheme.

**Comment by zzmp** [comment]
I think it's more important to note the issue than to think about whether a specific provider would allow a solution to it, because otherwise you'll just have very confused users who think that MetaMask is broken.

Is there a reason MetaMask makes this request from the background page instead of from the page trying to switch the chain? Or does it need to do so so that the popup will be able to interact with that chain without the page that originally added it?

**Comment by Sawanee250825** [comment]
# p

**Comment by Sawanee250825** [comment]
] Update rpc-api.md (PR #533)

**Comment by Gudahtt** [comment]
The "switch chain" method doesn't interact with the network at all. The "current chain" is purely a setting internal to MetaMask. The failure you're seeing is probably the background calling `eth_chainId` to verify the chain ID with the network.

We make that request from the background because _all_ network traffic goes through the background. We route all traffic through this one process to reduce overall network traffic for users that are using multiple dapps.

**Comment by Gudahtt** [comment]
I agree we should have some warning here for users about the origin allowlist. At the very least we should warn that it can cause problems. I'm just hesitant about being more specific than that without doing more testing, across Firefox and Chrome.

**Review by zzmp — COMMENTED** [review]
docs: clarify wallet_addEthereumChain edge case

**Comment by zzmp** [comment]
@Gudahtt I backed out the specificity so that this is now just a general warning with a note on the mechanism.

**Review by Gudahtt — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
