### PR TITLE
fix: incorrect `docsDir` in `.vuepress/config.js`

### PR DESCRIPTION
**Pull request by zgayjjf**
The `docsDir` of vuepress should be `docs` rather than `packages/docs/dist`.

### CODE REVIEW

**Comment by zgayjjf** [comment]
[MetaMask Docs](https://docs.metamask.io/guide/signing-data.html#sign-typed-data-v4)

You can click _Edit this page on GitHub_ at the bottom and it currently guides you to a 404 page, which confused a lot of developers.

@BboyAkers

**Review by BboyAkers — APPROVED** [review]
LGTM

**Comment by BboyAkers** [comment]
Thanks for catching this 🙂

**Comment by BboyAkers** [comment]
@ryanml can you approve this as well please? 🙂

**Review by rekmarks — APPROVED** [review]
LGTM!

**Comment by BboyAkers** [comment]
Any way we can get these Circle CI processes to run? @rekmarks

**Comment by Gudahtt** [comment]
Done!

**Pull request merged**
