### PR TITLE
Clarify info about versioning for signing data

### PR DESCRIPTION
**Pull request by pcowgill**

### CODE REVIEW

**Review by BboyAkers — APPROVED** [review]
LGTM

**Comment by BboyAkers** [comment]
@whymarrh getting this error on the ci/circleci build for the Algolia key. Isn't the key private? We can't merge until that passes

`ERROR: Algolia API key or index name not set.`

**Comment by whymarrh** [comment]
I'll take a look!

**Comment by whymarrh** [comment]
I've created #179 to fix the issue with the build, I can rebase this once that's merged.

**Comment by whymarrh** [comment]
Thanks @pcowgill!

**Pull request merged**
