### PR TITLE
fix: snaps transaction-insights missing dependencies

### PR DESCRIPTION
**Pull request by marvinmarnold**
Missing @metamask/snaps-types and @metamask/snaps-ui which are referenced later in index.ts.

### CODE REVIEW

**Comment by joaniefromtheblock** [comment]
Thank you for this helpful PR @marvinmarnold and for catching this. We'll update the docs accordingly.

**Comment by Montoya** [comment]
When using the latest template, the dependency is `@metamask/snaps-sdk`. The mentioned packages are deprecated in favor of this package. Please test the flow and see if it works with the latest template before making this change.

**Review by Montoya — CHANGES_REQUESTED** [review]
See above comment

**Comment by Montoya** [comment]
Closing in favor of #1206

**Pull request closed without merging**
