### PR TITLE
Document eth_sign discontinuation

### LINKED ISSUE #1313: Document eth_sign discontinuation
Once [`eth_sign` is discontinued](https://github.com/MetaMask/metamask-improvement-proposals/pull/42) (est. June 2024), update [`eth_sign` documentation](https://docs.metamask.io/wallet/concepts/signing-methods/#eth_sign) to note that it is no longer supported, even through advanced settings.

### PR DESCRIPTION
**Pull request by alexandratran**
# Description

Update `eth_sign` description to note that it is no longer supported.

## Issue(s) fixed

Fixes #1313 

## Preview

https://docs.metamask.io/1313-eth-sign-discontinuation/wallet/concepts/signing-methods/#eth_sign

## Checklist

Complete this checklist before merging your PR:

- [x] If this PR contains a major change to the documentation content, I have added an entry to the top of the ["What's new?"](https://github.com/MetaMask/metamask-docs/blob/main/docs/whats-new.md) page.
- [x] The proposed changes have been reviewed and approved by a member of the documentation team.

### CODE REVIEW

**Comment by vandan** [comment]
Only thought is to try and add a reference to the associated MIP for this change.
It's still an outstanding PR that needs to be reviewed/merged - should happen very soon: https://github.com/MetaMask/metamask-improvement-proposals/pull/42

**Review by joaniefromtheblock — APPROVED** [review]
LGTM

**Comment by alexandratran** [comment]
Added in a link for MIP-3, but the file is not ready due to autonumbering issues: https://github.com/MetaMask/metamask-improvement-proposals/blob/main/MIPs/mip-x.md.

Once that file is updated to `mip-3.md`, this PR should be ready to go.

**Review by vandan — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
