### PR TITLE
WIP: feat(docs): ACT-1532 - Create Pages for the Linea JSON-RPC methods dynamically

### PR DESCRIPTION
**Pull request by aednikanov**
# Description

Create Pages for the Linea JSON-RPC methods dynamically

[Ticket](https://infura.atlassian.net/browse/ACT-1532)

New sidebar items with dynamic pages can be found in `Services => Reference => Linea => JSON-RPC methods NEW`.

### CODE REVIEW

**Review by alexandratran — APPROVED** [review]

**Comment by bgravenorst** [comment]
I'm currently unable to test running the requests, but here are a few things I've noticed. 

- The left navigation is currently broken. When I expand Linea -> JSON-RPC methods and select a method, the left navigation resets and collapses my expanded menu.

- Bold formatting not being obeyed in method description. E.g https://metamask-docs-git-act-1532-create-linea-pag-ec2dff-metamask-web.vercel.app/services/reference/linea/json-rpc-methods/eth_estimateGas/

- For methods that accept block numbers or tags (e.g eth_estimateGas, eth_getBlockByNumber), I'm not sure the descriptions are displaying correctly. The spec appears to have a `oneOf` schema attached.

- For eth_maxPriorityFeePerGas, the schema of the Result in the spec is not displaying. https://github.com/INFURA/sot-network-methods/blob/main/blockchains/linea/openrpc.json#L5219

**Comment by TrofimovAnton85** [comment]
> I'm currently unable to test running the requests, but here are a few things I've noticed.
> 
> * The left navigation is currently broken. When I expand Linea -> JSON-RPC methods and select a method, the left navigation resets and collapses my expanded menu.
> * Bold formatting not being obeyed in method description. E.g https://metamask-docs-git-act-1532-create-linea-pag-ec2dff-metamask-web.vercel.app/services/reference/linea/json-rpc-methods/eth_estimateGas/
> * For methods that accept block numbers or tags (e.g eth_estimateGas, eth_getBlockByNumber), I'm not sure the descriptions are displaying correctly. The spec appears to have a `oneOf` schema attached.
> * For eth_maxPriorityFeePerGas, the schema of the Result in the spec is not displaying. https://github.com/INFURA/sot-network-methods/blob/main/blockchains/linea/openrpc.json#L5219

Thanks for the feedback!
We are currently working on the sidebar.
About the others:
- I checked and now we have the processing of bold text working on double asterisk symbols (** text **) and in the description of the eth_estimateGas/ method - single
- points 3, 4 are fixed and committed

**Comment by aednikanov** [comment]
@bgravenorst hello! Thanks for testing! I fixed the 1st item from your list as well.

**Comment by alexandratran** [comment]
Should we expect to be able to run and customize requests in this PR? It doesn't seem to work for me, only the example response displays the entire time (using the latest preview deployment):

https://github.com/user-attachments/assets/f420d3df-ed0c-483b-813e-a353231f57ff

Also, @TrofimovAnton85:

> I checked and now we have the processing of bold text working on double asterisk symbols (** text **) and in the description of the eth_estimateGas/ method - single

Can you enable italicized text using single asterisks or underscores (`*text*`) or (`_text_`), like in standard Markdown?

**Comment by TrofimovAnton85** [comment]
> Should we expect to be able to run and customize requests in this PR? It doesn't seem to work for me, only the example response displays the entire time (using the latest preview deployment):
> 
>  eth_feeHistory.mov 
> Also, @TrofimovAnton85:
> 
> > I checked and now we have the processing of bold text working on double asterisk symbols (** text **) and in the description of the eth_estimateGas/ method - single
> 
> Can you enable italicized text using single asterisks or underscores (`*text*`) or (`_text_`), like in standard Markdown?

@alexandratran , @bgravenorst Sorry maybe I missed something - but I checked the markdown standard here - https://www.markdownguide.org/basic-syntax/#:~:text=To%20bold%20text%2C%20add%20two,without%20spaces%20around%20the%20letters.&text=I%20just%20love%20**bold%20text**.
or is it outdated?

**Comment by TrofimovAnton85** [comment]
> Should we expect to be able to run and customize requests in this PR? It doesn't seem to work for me, only the example response displays the entire time (using the latest preview deployment):
> 
>  eth_feeHistory.mov 
> Also, @TrofimovAnton85:
> 
> > I checked and now we have the processing of bold text working on double asterisk symbols (** text **) and in the description of the eth_estimateGas/ method - single
> 
> Can you enable italicized text using single asterisks or underscores (`*text*`) or (`_text_`), like in standard Markdown?

Thanks for the feedback!
I added _italic_ support + some improvements to UI/UX for a request (now you can see the pending request state with the loader on the button).
More details on this thread: https://consensys.slack.com/archives/C075PCUF0TF/p1727786495606279

**Pull request closed without merging**
