### PR TITLE
feat(ref): added rpc-parser component to linea ref pages

### PR DESCRIPTION
**Pull request by TrofimovAnton85**
## Description

- Added **ParserOpenRPC** component for **Linea** reference pages **services/reference/linea/json-rpc-methods** ( `/eth_accounts` , `/eth_blocknumber` , `/eth_chainid` , `/eth_gasprice` , `/eth_maxpriorityfeepergas` , `/eth_syncing` )

## Test

- Go to pages and check the display of the new layout (content part / interactive part)
- To test the content => compare the content on the page with the corresponding method in the source JSON-RPC (https://sot-network-methods.vercel.app/specs/linea)
- To test the interactive part (send request):
  - need logged in to the test env https://infura-app-staging.vercel.app/ and that you have the Linea-mainnet network enabled
   - connect from reference page & check that your API key is displayed correctly
  
Screenshot 2024-10-01 at 13 29 17

### CODE REVIEW

**Review by m4sterbunny — COMMENTED** [review]
AFAIK, the reason that the Vercel build results in unsuccessful CURL requests is that the URL is updated to dev
mainnet.infura becomes mainnet.dev.infura --> I think this is causing the difference in behavior between Vercel build and local build @TrofimovAnton85

**Review by alexandratran — APPROVED** [review]

**Comment by TrofimovAnton85** [comment]
> AFAIK, the reason that the Vercel build results in unsuccessful CURL requests is that the URL is updated to dev mainnet.infura becomes mainnet.dev.infura --> I think this is causing the difference in behavior between Vercel build and local build @TrofimovAnton85

About endpoints:
1) https://linea-mainnet.dev.infura.org - this is the endpoint for dev/test env
2) https://linea-mainnet.infura.io - this is the endpoint for prod env
---
as discussed in Slack, we need to merge this PR and test it on prod

**Comment by m4sterbunny** [comment]
Testing this in prod with Infura/MM signin

**Comment by m4sterbunny** [comment]
image
The schema referenced in eth_chainID provides the string's pattern, this data is lost

**Comment by m4sterbunny** [comment]
eth_gasPrice is returning the value 0xe4e1c07 in hexadecimal, which GPT converts to 239,999,999 in decimal== much higher than the current average Ethereum gas price of 34.48 gwei.

**Pull request merged**
