### PR TITLE
Add "Wallet API" terminology

### LINKED ISSUE #1120: Add "Wallet API" terminology
Update docs where applicable to describe/reference the Provider API + JSON-RPC API as the "Wallet API." Also add a "Wallet API" category to the reference section, and place the Provider and JSON-RPC references under that category.

### PR DESCRIPTION
**Pull request by alexandratran**
Add "Wallet API" terminology. Fixes #1120.

This PR is conjunction with https://github.com/MetaMask/api-specs/pull/185, which updates the JSON-RPC reference index page to mention the Wallet API.

Preview: https://docs.metamask.io/1120-wallet-api/

### CODE REVIEW

**Comment by vandan** [comment]
This page should match the tags we describe on the new index page's description (api-specs change): https://docs.metamask.io/1120-wallet-api/wallet/concepts/wallet-api/

**Comment by alexandratran** [comment]
@vandan Thanks for catching, I just removed it in the concepts page, in favor of the list on the new index page.

**Comment by alexandratran** [comment]
@vandan Thanks for catching, I just removed it in the concepts page, in favor of the list on the new index page.

**Review by joaniefromtheblock — APPROVED** [review]
lgtm

**Review by vandan — APPROVED** [review]
Thanks for applying the updates. Looks nice and consistent now.

**Pull request merged**
