### PR TITLE
fix: add link onboarding document in snap allowlist

### LINKED ISSUE #1486: Missing Link to Onboarding Form in Snaps Allowlisting Tutorial
**Description:**

In the Snaps allowlisting tutorial, we currently link to the form that requests Snaps information, but we do not share the link to the onboarding form. This causes a break in the expected flow for users.

**Current Flow:**
1. Snaps directory information form: [https://go.metamask.io/snaps-directory-request](https://go.metamask.io/snaps-directory-request)

**Expected Flow:**
1. Onboarding form: [https://feedback.metamask.io/snaps-onboarding/](https://feedback.metamask.io/snaps-onboarding/)
2. Snaps directory information form: [https://go.metamask.io/snaps-directory-request](https://go.metamask.io/snaps-directory-request)

**Proposed Solutions:**
1. Modify the description in the Snaps directory information form to include a link to the onboarding form.
2. Update the `snaps/how-to/get-allowlisted/` page section `1. Submit your Snap` as follows:

**Current Text:**
> Fill out the MetaMask Snaps Directory Information form. The form requests information about your Snap, including the following:

**Proposed Text:**
> Fill out both the Snaps onboarding form and the MetaMask Snaps Directory Information form. The forms request information about your Snap, including the following:

---

**Steps to Reproduce:**
1. Navigate to the Snaps allowlisting tutorial.
2. Note the missing link to the onboarding form.

**Expected Behavior:**
The tutorial should guide users to complete both forms in the correct order, ensuring snaps onboarding team have all necessary information.

**Additional Context:**
Link to the onboarding form: [https://feedback.metamask.io/snaps-onboarding/](https://feedback.metamask.io/snaps-onboarding/)

Thank you for addressing this issue to improve the user experience for Snap developers.

### PR DESCRIPTION
**Pull request by khanti42**
# Description

Update the description of the allowlisting process.

## Issue(s) fixed

Closes #1486 

## Checklist

Complete this checklist before merging your PR:

- [ ] If this PR contains a major change to the documentation content, I have added an entry to the top of the ["What's new?"](https://github.com/MetaMask/metamask-docs/blob/main/docs/whats-new.md) page.
- [ ] The proposed changes have been reviewed and approved by a member of the documentation team.

### CODE REVIEW

**Review by joaniefromtheblock — APPROVED** [review]
LGTM

**Comment by joaniefromtheblock** [comment]
@Montoya, can this be approved?

**Comment by alexandratran** [comment]
I'll take a look at this and merge today. Requires minor edits.

**Review by Montoya — DISMISSED** [review]

**Comment by Montoya** [comment]
@joaniefromtheblock Yes all good from me

**Review by alexandratran — APPROVED** [review]
Based on this context from @khanti42, it seems that the Onboarding form should be introduced to the user much earlier than the Directory form, rather than in the same location:

> The onboarding form is intended for teams that are just starting out and want to develop a snap—they might not even have a name for their snap yet but have a company and product in mind. On the other hand, the snaps directory information form is specific to the snap itself, which should be filled out later in the development process.
>
> Ideally, we'd like to engage with builders early in their journey, rather than waiting until they've completed their snap. ...
>
> My goal is to gather information from teams as early as possible, even before they finalise the snap's name. ... I'm looking for a way to encourage teams to provide their information before or at the early stages of snap development.

I've moved the Onboarding form out of the "Submit your Snap [for allowlisting]" step and into the "Next steps" section of the quickstart in order to introduce it much earlier in the Snap development process. I've also included it as a prerequisite before allowlisting to remind users to fill it out first.

**Review by Montoya — APPROVED** [review]

**Comment by Montoya** [comment]
good to merge

**Pull request merged**
