### PR TITLE
Add flask-only UI elements

### PR DESCRIPTION
**Pull request by ziad-saab**
New admonition `:::flaskOnly` adds a block that looks like this:

image

New custom prop for sidebar items `flask_only` adds tag in the sidebar, like this:

image

This custom prop can be added either in the Markdown file as frontmatter:

```
description: Learn about the Snaps Keyring API.
sidebar_position: 6
sidebar_custom_props:
  flask_only: true
```

It can also be added in a sidebar config file under `customProps` for the target item.

### CODE REVIEW

**Comment by Montoya** [comment]
This seems to work fine but I cannot build and test locally. Running `yarn install` produces the following error: 

```
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 6s 464ms
no allowed lifecycle scripts found in configuration
running lifecycle scripts for top level package
Error: command failed
    at ChildProcess.<anonymous> (/Users/consensys-cm/Documents/GitHub/metamask-docs/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:332:12) {
  cmd: 'sh',
  args: [ '-c', 'cd external/keyring-api && yarn install' ],
  code: 1,
  signal: null,
  stdout: '➤ YN0000: ┌ Resolution step\n' +
    "➤ YN0002: │ @algolia/autocomplete-core@npm:1.9.3 doesn't provide @algolia/client-search (pbc410), requested by @algolia/autocomplete-shared\n" +
    "➤ YN0002: │ @algolia/autocomplete-core@npm:1.9.3 doesn't provide algoliasearch (p8ad5b), requested by @algolia/autocomplete-shared\n" +
    "➤ YN0002: │ @algolia/autocomplete-core@npm:1.9.3 doesn't provide search-insights (pfdb70), requested by @algolia/autocomplete-plugin-algolia-insights\n" +
    "➤ YN0002: │ @algolia/autocomplete-plugin-algolia-insights@npm:1.9.3 [e43f4] doesn't provide @algolia/client-search (pdf3b9), requested by @algolia/autocomplete-shared\n" +
    "➤ YN0002: │ @algolia/autocomplete-plugin-algolia-insights@npm:1.9.3 [e43f4] doesn't provide algoliasearch (p0f6bb), requested by @algolia/autocomplete-shared\n" +
    "➤ YN0002: │ @docsearch/react@npm:3.5.1 [94234] doesn't provide @algolia/client-search (pbe368), requested by @algolia/autocomplete-preset-algolia\n" +
    "➤ YN0002: │ @metamask/docusaurus-openrpc@npm:0.2.2 [5b291] doesn't provide webpack (p2226c), requested by node-polyfill-webpack-plugin\n" +
    "➤ YN0002: │ @stoplight/mosaic-code-viewer@npm:1.41.0 [d76bd] doesn't provide react-dom (p83d42), requested by use-resize-observer\n" +
    "➤ YN0002: │ @stoplight/mosaic@npm:1.41.0 [d76bd] doesn't provide react-dom (p397eb), requested by use-resize-observer\n" +
    "➤ YN0002: │ docusaurus-plugin-typedoc@npm:1.0.0-next.15 [5b291] doesn't provide react (p69412), requested by @docusaurus/types\n" +
    "➤ YN0002: │ docusaurus-plugin-typedoc@npm:1.0.0-next.15 [5b291] doesn't provide react-dom (p58957), requested by @docusaurus/types\n" +
    "➤ YN0002: │ metamask-docs@workspace:. doesn't provide webpack (pd251c), requested by node-polyfill-webpack-plugin\n" +
    "➤ YN0002: │ react-overflow-list@npm:0.5.0 [ef683] doesn't provide react-dom (p37d2d), requested by react-use\n" +
    "➤ YN0002: │ react-overflow-list@npm:0.5.0 [f3b99] doesn't provide react-dom (pfa0c4), requested by react-use\n" +
    '➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code\n' +
    '➤ YN0000: └ Completed\n' +
    '➤ YN0000: ┌ Fetch step\n' +
    '➤ YN0000: └ Completed\n' +
    '➤ YN0000: ┌ Link step\n' +
    '➤ YN0000: └ Completed in 0s 298ms',
  stderr: "Error: ENOENT: no such file or directory, open '/Users/consensys-cm/Documents/GitHub/metamask-docs/external/keyring-api/package.json'\n" +
    '    at Object.openSync (node:fs:589:3)\n' +
    '    at readFileSync (node:fs:457:35)\n' +
    '    at getDependencies (/Users/consensys-cm/Documents/GitHub/metamask-docs/node_modules/@lavamoat/aa/src/index.js:73:26)\n' +
    '    at processOnePackageInLogicalTree (/Users/consensys-cm/Documents/GitHub/metamask-docs/node_modules/@lavamoat/aa/src/index.js:109:22)\n' +
    '    at walkDependencyTreeForBestLogicalPaths (/Users/consensys-cm/Documents/GitHub/metamask-docs/node_modules/@lavamoat/aa/src/index.js:97:5)\n' +
    '    at loadCanonicalNameMap (/Users/consensys-cm/Documents/GitHub/metamask-docs/node_modules/@lavamoat/aa/src/index.js:47:26)\n' +
    '    at loadAllPackageConfigurations (/Users/consensys-cm/Documents/GitHub/metamask-docs/node_modules/@lavamoat/allow-scripts/src/index.js:374:31)\n' +
    '    at runAllowedPackages (/Users/consensys-cm/Documents/GitHub/metamask-docs/node_modules/@lavamoat/allow-scripts/src/index.js:84:13)\n' +
    '    at start (/Users/consensys-cm/Documents/GitHub/metamask-docs/node_modules/@lavamoat/allow-scripts/src/cli.js:23:13)\n' +
    '    at Object.<anonymous> (/Users/consensys-cm/Documents/GitHub/metamask-docs/node_modules/@lavamoat/allow-scripts/src/cli.js:8:1) {\n' +
    '  errno: -2,\n' +
    "  syscall: 'open',\n" +
    "  code: 'ENOENT',\n" +
    "  path: '/Users/consensys-cm/Documents/GitHub/metamask-docs/external/keyring-api/package.json'\n" +
    '}',
  event: 'postinstall',
  script: 'cd external/keyring-api && yarn install',
  pkgid: 'metamask-docs@0.0.0',
  path: '/Users/consensys-cm/Documents/GitHub/metamask-docs'
}
```

**Comment by Montoya** [comment]
Update: after running `git submodule update` everything worked fine

**Review by Montoya — APPROVED** [review]
LGTM

**Review by alexandratran — COMMENTED** [review]
Can we add this label to this page too? https://docs.metamask.io/snaps/how-to/use-keyring-api/

**Comment by Montoya** [comment]
Screenshot 2023-09-27 at 1 12 33 PM

Oh no the label falls apart in the dropdown. Can we make it top level only???

**Comment by ziad-saab** [comment]
@Montoya yep, it's my 💩 CSS. Fixing. Thank you!

**Review by alexandratran — APPROVED** [review]
lgtm!

**Review by vandan — APPROVED** [review]
These changes look good to me.

**Pull request merged**
